- name: get list of available groups (/etc/groups)
  shell: 'getent group|cut -d: -f1|grep -E "(^{{ item.posix_users_groups|join("$|^")}}$)" | sed -n -e "H;\${x;s/\n/,/g;s/^,//;p;}"'
  become: False
  changed_when: False
  register: posix_users_available_groups
  check_mode: false
  with_items: "{{ common_users_accounts }}"
  when: common_users_accounts is defined and item.posix_users_groups is defined and ( posix_users_only_handle_my_user and item.name == ansible_user_id)

- name: add users to available groups (/etc/groups)
  user: name={{ item.item.name }} groups={{ item.stdout }}
  with_items: "{{ posix_users_available_groups.results }}"
  when: item.stdout is defined
  notify: update /etc/passwd timestamp
  register: 
  become: true
  
- name: update /etc/passwd timestamp
  file: path={{ item }} state=touch
  with_items:
   - /etc/passwd
  become: true

- name: register ansible_ssh_user used for this machine
  shell: echo ${USER}
  changed_when: False
  become: false
  register: common_ansible_ansible_ssh_user
  check_mode: false

## fixme: we should check if controlpath is setup correct in ../../../../ansible.cfg (we should expect ansible_ssh_ControlPath or in any other directory thats listed in http://docs.ansible.com/ansible/latest/intro_configuration.html
## fixme: this handler should be a library
- name: restart ssh multiplexer
  become: false
  shell: 
   cmd: "./ssh-control-connection-stop.sh {{ ansible_ssh_ControlPath }} {{ hostvars[inventory_hostname]['ansible_ssh_host']|default(inventory_hostname) }}"
   chdir: "{{ role_path }}/files"
  delegate_to: 127.0.0.1
  changed_when: False

- name: make sure we are updating users with new groups
  set_fact:
    posix_users_up2date: false
